const assert=require('node:assert/strict');
const E=require('./dist/engine.js');
const m='2026-10';
const s=E.fresh(),mo=E.month(s,m);
s.members[2].start='2025-01-01';
mo.requests['s3:5']='E';mo.requests['s3:12']='F';
mo.schedule['s1:3']='C';mo.locks['s1:3']=true;
mo.previous.s4='D';
s.members[10].end='2026-10-10';
s.members[11].weekdays=[1,2,3,4,5];
let issues=E.generate(s,m);
assert.equal(mo.schedule['s3:5'],'E');assert.equal(mo.schedule['s3:12'],'F');
assert.equal(mo.schedule['s1:3'],'C');assert.equal(mo.schedule['s4:1'],'d');assert.equal(mo.schedule['s4:2'],'E');
assert.equal(issues.filter(x=>['request','sequence','availability','inactive','run','night'].includes(x.type)).length,0,JSON.stringify(issues));
assert.deepEqual(E.checkData(E.copy(s)),s);
const t=E.fresh(),tm=E.month(t,m);for(const p of t.members)tm.requests[E.key(p.id,5)]='E';
assert(E.generate(t,m).some(x=>x.type==='coverage'&&x.d===5));
tm.locks['s1:5']=true;tm.schedule['s1:5']='B';assert.throws(()=>E.generate(t,m),/固定/);
assert.equal(E.days('2028-02'),29);
console.log('PASS: requests, paid leave, fixed cells, overnight carry, weekdays, tenure, validation, shortage, conflicting locks, round-trip');
const c=E.fresh(),cm=E.month(c,'2028-02');
cm.schedule={'s1:1':'G','s2:1':'B','s3:1':'B','s4:1':'C','s5:1':'D','s6:1':'d','s7:1':'/B','s8:1':'F','s9:1':'E'};
c.members[11].end='2028-01-31';cm.schedule['s12:1']='G';
let counts=E.dailyCounts(c,'2028-02');
assert.equal(counts.length,29);assert.equal(counts[0].counts.G,1);assert.equal(counts[0].counts.B,2);assert.equal(counts[0].counts['/B'],1);assert.equal(counts[0].counts.D,1);assert.equal(counts[0].counts.d,1);assert.equal(counts[0].counts.blank,2);
cm.schedule['s2:1']='G';assert.equal(E.dailyCounts(c,'2028-02')[0].counts.G,2);assert.equal(E.dailyCounts(c,'2028-02')[0].counts.B,1);
assert.equal(E.dailyCounts(c,'2028-03')[0].counts.G,0);assert.equal(Object.hasOwn(E.shifts,'A'),false);
assert.deepEqual(E.checkData(E.copy(c)),c);const legacyA=E.copy(c);legacyA.months['2028-02'].schedule['s1:1']='A';assert.throws(()=>E.checkData(legacyA),/勤務記号/);
console.log('PASS: exact-code daily counts, A removal, tenure exclusion, leap month, separate months and unsupported legacy A rejection');
assert.equal(E.equivalentTenths('G'),7);assert.equal(E.equivalentTenths('I'),8);
for(const code of ['B','C','D','d'])assert.equal(E.equivalentTenths(code),10);
for(const code of ['A','E','F','/B','/C','',undefined])assert.equal(E.equivalentTenths(code),0);
const eq=E.fresh(),eqm=E.month(eq,'2026-10');
const cases=[['G','G'],['B','B','B','G','G','G','I'],['B','B','B','B','B','B'],['B','B','B','B','G','G','G','I'],['B','B','B','B','B','B','B']];
cases.forEach((codes,i)=>codes.forEach((code,j)=>eqm.schedule[E.key(eq.members[j].id,i+1)]=code));
assert.deepEqual(E.dailyEquivalent(eq,'2026-10').slice(0,5).map(r=>[r.value,r.status]),[['1.4','low'],['5.9','low'],['6.0','near'],['6.9','near'],['7.0','pass']]);
assert(E.validate(eq,'2026-10').some(x=>x.type==='equivalent'&&x.d===4));
assert(!E.validate(eq,'2026-10').some(x=>x.type==='equivalent'&&x.d===5));
eqm.schedule['s1:5']='E';assert.equal(E.dailyEquivalent(eq,'2026-10')[4].value,'6.0');
eq.members[1].end='2026-09-30';assert.equal(E.dailyEquivalent(eq,'2026-10')[4].value,'5.0');
console.log('PASS: individual truncation, eligible codes, 5.9/6.0/6.9/7.0 thresholds, edits, tenure and validation');
